export default {
  PrivacyIntro: {
    en: 'At {appName}, your privacy is our priority. This privacy policy explains how we collect, use, and protect your personal data in accordance with the GDPR.',
    es: 'En {appName}, su privacidad es nuestra prioridad. Esta política de privacidad explica cómo recopilamos, utilizamos y protegemos sus datos personales de acuerdo con el RGPD.',
    nl: 'Bij {appName} is uw privacy onze prioriteit. Dit privacybeleid legt uit hoe we uw persoonlijke gegevens verzamelen, gebruiken en beschermen in overeenstemming met de AVG.',
    fr: 'Chez {appName}, votre vie privée est notre priorité. Cette politique de confidentialité explique comment nous collectons, utilisons et protégeons vos données personnelles conformément au RGPD.',
    de: 'Bei {appName} hat Ihre Privatsphäre oberste Priorität. Diese Datenschutzrichtlinie erklärt, wie wir Ihre persönlichen Daten gemäß der DSGVO sammeln, verwenden und schützen.',
    it: 'Presso {appName}, la tua privacy è la nostra priorità. Questa politica sulla privacy spiega come raccogliamo, utilizziamo e proteggiamo i tuoi dati personali in conformità con il GDPR.',
    ru: 'В {appName} ваша конфиденциальность является нашим приоритетом. Эта политика конфиденциальности объясняет, как мы собираем, используем и защищаем ваши личные данные в соответствии с GDPR.',
    pt: 'Na {appName}, a sua privacidade é nossa prioridade. Esta política de privacidade explica como recolhemos, utilizamos e protegemos os seus dados pessoais em conformidade com o RGPD.',
    pl: 'W {appName} prywatność jest naszym priorytetem. Niniejsza polityka prywatności wyjaśnia, w jaki sposób gromadzimy, wykorzystujemy i chronimy Twoje dane osobowe zgodnie z RODO.',
    ro: 'La {appName}, confidențialitatea ta este prioritatea noastră. Această politică de confidențialitate explică modul în care colectăm, folosim și protejăm datele tale personale în conformitate cu GDPR.',
    sv: 'På {appName} är din integritet vår prioritet. Denna integritetspolicy förklarar hur vi samlar in, använder och skyddar dina personuppgifter i enlighet med GDPR.',
  },
  DataCollection: {
    en: '1. Data Collection',
    es: '1. Recopilación de Datos',
    nl: '1. Gegevensverzameling',
    fr: '1. Collecte de données',
    de: '1. Datenerfassung',
    it: '1. Raccolta Dati',
    ru: '1. Сбор данных',
    pt: '1. Coleta de Dados',
    pl: '1. Zbieranie danych',
    ro: '1. Colectarea datelor',
    sv: '1. Datainsamling',
  },
  DataCollectionDetails: {
    en: 'We collect only the necessary information to provide our services, such as your name, email address, and information related to the exams you create or participate in.',
    es: 'Recopilamos solo la información necesaria para proporcionar nuestros servicios, como su nombre, dirección de correo electrónico e información relacionada con los exámenes que crea o en los que participa.',
    nl: 'We verzamelen alleen de noodzakelijke informatie om onze diensten te leveren, zoals uw naam, e-mailadres en informatie met betrekking tot de examens die u maakt of waaraan u deelneemt.',
    fr: 'Nous ne collectons que les informations nécessaires pour fournir nos services, telles que votre nom, adresse e-mail et les informations relatives aux examens que vous créez ou auxquels vous participez.',
    de: 'Wir erfassen nur die notwendigen Informationen, um unsere Dienste bereitzustellen, wie Ihren Namen, Ihre E-Mail-Adresse und Informationen zu den Prüfungen, die Sie erstellen oder an denen Sie teilnehmen.',
    it: 'Raccogliamo solo le informazioni necessarie per fornire i nostri servizi, come il tuo nome, indirizzo email e informazioni relative agli esami che crei o a cui partecipi.',
    ru: 'Мы собираем только необходимые данные, чтобы предоставлять наши услуги, такие как ваше имя, адрес электронной почты и информация, связанная с экзаменами, которые вы создаете или в которых участвуете.',
    pt: 'Recolhemos apenas as informações necessárias para fornecer os nossos serviços, como o seu nome, endereço de e-mail e informações relacionadas com os exames que cria ou participa.',
    pl: 'Zbieramy tylko niezbędne informacje do świadczenia naszych usług, takie jak imię i nazwisko, adres e-mail oraz informacje dotyczące egzaminów, które tworzysz lub w których bierzesz udział.',
    ro: 'Colectăm doar informațiile necesare pentru a furniza serviciile noastre, cum ar fi numele, adresa de e-mail și informațiile legate de examenele pe care le creezi sau la care participi.',
    sv: 'Vi samlar endast in nödvändig information för att tillhandahålla våra tjänster, såsom ditt namn, e-postadress och information om de prov du skapar eller deltar i.',
  },
  DataUsage: {
    en: '2. Data Usage',
    es: '2. Uso de Datos',
    nl: '2. Gegevensgebruik',
    fr: '2. Utilisation des données',
    de: '2. Datennutzung',
    it: '2. Uso dei Dati',
    ru: '2. Использование данных',
    pt: '2. Uso de Dados',
    pl: '2. Wykorzystanie danych',
    ro: '2. Utilizarea datelor',
    sv: '2. Användning av data',
  },
  DataUsageDetails: {
    en: 'Your personal data will only be used to enhance your experience on the platform and for service-related purposes such as communication, user support, and improving our features.',
    es: 'Sus datos personales se utilizarán únicamente para mejorar su experiencia en la plataforma y para fines relacionados con el servicio, como la comunicación, el soporte al usuario y la mejora de nuestras funciones.',
    nl: 'Uw persoonlijke gegevens worden alleen gebruikt om uw ervaring op het platform te verbeteren en voor servicegerelateerde doeleinden, zoals communicatie, gebruikersondersteuning en het verbeteren van onze functies.',
    fr: 'Vos données personnelles ne seront utilisées que pour améliorer votre expérience sur la plateforme et à des fins liées au service, telles que la communication, l\'assistance utilisateur et l\'amélioration de nos fonctionnalités.',
    de: 'Ihre persönlichen Daten werden nur verwendet, um Ihre Erfahrung auf der Plattform zu verbessern und für dienstbezogene Zwecke wie Kommunikation, Benutzersupport und die Verbesserung unserer Funktionen.',
    it: 'I tuoi dati personali verranno utilizzati solo per migliorare la tua esperienza sulla piattaforma e per scopi legati al servizio come comunicazione, supporto utenti e miglioramento delle nostre funzionalità.',
    ru: 'Ваши персональные данные будут использоваться только для улучшения вашего опыта на платформе и в служебных целях, таких как связь, поддержка пользователей и улучшение наших функций.',
    pt: 'Os seus dados pessoais serão utilizados apenas para melhorar a sua experiência na plataforma e para fins relacionados com o serviço, como comunicação, suporte ao utilizador e melhoria das nossas funcionalidades.',
    pl: 'Twoje dane osobowe będą wykorzystywane wyłącznie w celu poprawy jakości korzystania z platformy oraz w celach związanych z usługami, takich jak komunikacja, wsparcie użytkowników i ulepszanie naszych funkcji.',
    ro: 'Datele tale personale vor fi utilizate doar pentru a îmbunătăți experiența pe platformă și în scopuri legate de servicii, cum ar fi comunicarea, asistența pentru utilizatori și îmbunătățirea funcțiilor noastre.',
    sv: 'Dina personuppgifter kommer endast att användas för att förbättra din upplevelse på plattformen och för tjänsterelaterade ändamål såsom kommunikation, användarstöd och förbättring av våra funktioner.',
  },
  DataSharing: {
    en: '3. Data Sharing',
    es: '3. Compartición de Datos',
    nl: '3. Gegevensdeling',
    fr: '3. Partage de données',
    de: '3. Datenweitergabe',
    it: '3. Condivisione Dati',
    ru: '3. Передача данных',
    pt: '3. Compartilhamento de Dados',
    pl: '3. Udostępnianie danych',
    ro: '3. Partajarea datelor',
    sv: '3. Delning av data',
  },
  DataSharingDetails: {
    en: 'We do not share your personal data with third parties, except when required by law or when necessary for the platform’s functionality (e.g., hosting services). In such cases, we ensure that these third parties are GDPR-compliant.',
    es: 'No compartimos sus datos personales con terceros, excepto cuando lo exija la ley o cuando sea necesario para el funcionamiento de la plataforma (por ejemplo, servicios de alojamiento). En tales casos, nos aseguramos de que estos terceros cumplan con el RGPD.',
    nl: 'We delen uw persoonlijke gegevens niet met derden, behalve wanneer dit wettelijk vereist is of wanneer dit nodig is voor de functionaliteit van het platform (bijv. hostingdiensten). In dergelijke gevallen zorgen we ervoor dat deze derden voldoen aan de AVG.',
    fr: 'Nous ne partageons pas vos données personnelles avec des tiers, sauf lorsque la loi l\'exige ou lorsque cela est nécessaire pour le bon fonctionnement de la plateforme (par exemple, services d\'hébergement). Dans ces cas, nous veillons à ce que ces tiers respectent le RGPD.',
    de: 'Wir geben Ihre persönlichen Daten nicht an Dritte weiter, es sei denn, dies ist gesetzlich vorgeschrieben oder für die Funktionalität der Plattform erforderlich (z. B. Hosting-Dienste). In solchen Fällen stellen wir sicher, dass diese Dritten DSGVO-konform sind.',
    it: 'Non condividiamo i tuoi dati personali con terze parti, tranne quando richiesto dalla legge o quando necessario per la funzionalità della piattaforma (ad esempio, servizi di hosting). In tal caso, ci assicuriamo che queste terze parti siano conformi al GDPR.',
    ru: 'Мы не передаем ваши персональные данные третьим лицам, за исключением случаев, предусмотренных законом, или когда это необходимо для функционирования платформы (например, хостинговые услуги). В таких случаях мы гарантируем, что эти третьи лица соответствуют требованиям GDPR.',
    pt: 'Não partilhamos os seus dados pessoais com terceiros, exceto quando exigido por lei ou quando necessário para a funcionalidade da plataforma (por exemplo, serviços de hospedagem). Nesses casos, garantimos que esses terceiros estejam em conformidade com o RGPD.',
    pl: 'Nie udostępniamy Twoich danych osobowych stronom trzecim, z wyjątkiem sytuacji wymaganych przez prawo lub gdy jest to konieczne do funkcjonowania platformy (np. usługi hostingowe). W takich przypadkach zapewniamy, że te strony trzecie są zgodne z RODO.',
    ro: 'Nu partajăm datele tale personale cu terți, cu excepția cazurilor impuse de lege sau necesare pentru funcționalitatea platformei (de exemplu, servicii de găzduire). În astfel de cazuri, ne asigurăm că aceste terțe părți respectă GDPR.',
    sv: 'Vi delar inte dina personuppgifter med tredje part, förutom när det krävs enligt lag eller när det är nödvändigt för plattformens funktionalitet (t.ex. värdtjänster). I sådana fall ser vi till att dessa tredje parter följer GDPR.',
  },
  DataSecurity: {
    en: '4. Data Security',
    es: '4. Seguridad de Datos',
    nl: '4. Gegevensbeveiliging',
    fr: '4. Sécurité des données',
    de: '4. Datensicherheit',
    it: '4. Sicurezza dei Dati',
    ru: '4. Безопасность данных',
    pt: '4. Segurança de Dados',
    pl: '4. Bezpieczeństwo danych',
    ro: '4. Securitatea datelor',
    sv: '4. Datasäkerhet',
  },
  DataSecurityDetails: {
    en: 'We take appropriate measures to protect your data from unauthorized access, alteration, or disclosure. All data is stored in secure environments with encryption where applicable.',
    es: 'Tomamos las medidas adecuadas para proteger sus datos contra el acceso, la alteración o la divulgación no autorizados. Todos los datos se almacenan en entornos seguros con cifrado cuando corresponde.',
    nl: 'We nemen passende maatregelen om uw gegevens te beschermen tegen ongeoorloofde toegang, wijziging of openbaarmaking. Alle gegevens worden opgeslagen in veilige omgevingen met encryptie waar van toepassing.',
    fr: 'Nous prenons les mesures appropriées pour protéger vos données contre tout accès non autorisé, toute altération ou toute divulgation. Toutes les données sont stockées dans des environnements sécurisés avec chiffrement lorsque cela est applicable.',
    de: 'Wir ergreifen geeignete Maßnahmen, um Ihre Daten vor unbefugtem Zugriff, Änderungen oder Offenlegungen zu schützen. Alle Daten werden in sicheren Umgebungen gespeichert und gegebenenfalls verschlüsselt.',
    it: 'Adottiamo le misure appropriate per proteggere i tuoi dati da accessi, alterazioni o divulgazioni non autorizzati. Tutti i dati sono conservati in ambienti sicuri con crittografia ove applicabile.',
    ru: 'Мы принимаем соответствующие меры для защиты ваших данных от несанкционированного доступа, изменения или раскрытия. Все данные хранятся в безопасных средах с использованием шифрования, если это применимо.',
    pt: 'Tomamos medidas apropriadas para proteger os seus dados contra o acesso, alteração ou divulgação não autorizados. Todos os dados são armazenados em ambientes seguros com encriptação, quando aplicável.',
    pl: 'Podejmujemy odpowiednie środki w celu ochrony Twoich danych przed nieautoryzowanym dostępem, zmianą lub ujawnieniem. Wszystkie dane są przechowywane w bezpiecznych środowiskach z szyfrowaniem, jeśli dotyczy.',
    ro: 'Luăm măsurile adecvate pentru a-ți proteja datele împotriva accesului, modificării sau divulgării neautorizate. Toate datele sunt stocate în medii securizate, cu criptare acolo unde este cazul.',
    sv: 'Vi vidtar lämpliga åtgärder för att skydda dina data från obehörig åtkomst, ändring eller avslöjande. All data lagras i säkra miljöer med kryptering där det är tillämpligt.',
  },
  YourRights: {
    en: '5. Your Rights',
    es: '5. Sus Derechos',
    nl: '5. Uw rechten',
    fr: '5. Vos droits',
    de: '5. Ihre Rechte',
    it: '5. I tuoi diritti',
    ru: '5. Ваши права',
    pt: '5. Os seus direitos',
    pl: '5. Twoje prawa',
    ro: '5. Drepturile tale',
    sv: '5. Dina rättigheter',
  },
  YourRightsDetails: {
    en: 'You have the right to access, modify, or delete your personal data at any time. You can contact us to exercise these rights, and we will comply with your request in accordance with GDPR guidelines.',
    es: 'Tiene derecho a acceder, modificar o eliminar sus datos personales en cualquier momento. Puede contactarnos para ejercer estos derechos, y cumpliremos con su solicitud de acuerdo con las pautas del RGPD.',
    nl: 'U heeft het recht om uw persoonlijke gegevens op elk moment in te zien, te wijzigen of te verwijderen. U kunt contact met ons opnemen om deze rechten uit te oefenen, en wij zullen aan uw verzoek voldoen in overeenstemming met de AVG-richtlijnen.',
    fr: 'Vous avez le droit d\'accéder à vos données personnelles, de les modifier ou de les supprimer à tout moment. Vous pouvez nous contacter pour exercer ces droits, et nous nous conformerons à votre demande conformément aux directives du RGPD.',
    de: 'Sie haben das Recht, Ihre persönlichen Daten jederzeit einzusehen, zu ändern oder zu löschen. Sie können uns kontaktieren, um diese Rechte auszuüben, und wir werden Ihrem Antrag gemäß den DSGVO-Richtlinien nachkommen.',
    it: 'Hai il diritto di accedere, modificare o eliminare i tuoi dati personali in qualsiasi momento. Puoi contattarci per esercitare questi diritti e ci conformeremo alla tua richiesta in conformità con le linee guida del GDPR.',
    ru: 'Вы имеете право в любое время получить доступ к своим персональным данным, изменить их или удалить. Вы можете связаться с нами, чтобы воспользоваться этими правами, и мы выполним ваш запрос в соответствии с руководящими принципами GDPR.',
    pt: 'Tem o direito de aceder, modificar ou eliminar os seus dados pessoais a qualquer momento. Pode contactar-nos para exercer esses direitos e cumpriremos o seu pedido de acordo com as diretrizes do RGPD.',
    pl: 'Masz prawo do dostępu do swoich danych osobowych, ich modyfikacji lub usunięcia w dowolnym momencie. Możesz się z nami skontaktować w celu skorzystania z tych praw, a my spełnimy Twoją prośbę zgodnie z wytycznymi RODO.',
    ro: 'Ai dreptul să accesezi, modifici sau ștergi datele tale personale în orice moment. Ne poți contacta pentru a-ți exercita aceste drepturi, iar noi ne vom conforma cererii tale în conformitate cu liniile directoare GDPR.',
    sv: 'Du har rätt att när som helst komma åt, ändra eller radera dina personuppgifter. Du kan kontakta oss för att utöva dessa rättigheter, och vi kommer att följa din begäran i enlighet med GDPR-riktlinjerna.',
  },
  MoreInfo: {
    en: 'For more information on how we protect your data, please contact our support team.',
    es: 'Para obtener más información sobre cómo protegemos sus datos, comuníquese con nuestro equipo de soporte.',
    nl: 'Voor meer informatie over hoe we uw gegevens beschermen, kunt u contact opnemen met ons ondersteuningsteam.',
    fr: 'Pour plus d\'informations sur la façon dont nous protégeons vos données, veuillez contacter notre équipe d\'assistance.',
    de: 'Für weitere Informationen darüber, wie wir Ihre Daten schützen, wenden Sie sich bitte an unser Support-Team.',
    it: 'Per ulteriori informazioni su come proteggiamo i tuoi dati, contatta il nostro team di supporto.',
    ru: 'Для получения дополнительной информации о том, как мы защищаем ваши данные, пожалуйста, свяжитесь с нашей службой поддержки.',
    pt: 'Para obter mais informações sobre como protegemos os seus dados, entre em contato com a nossa equipe de suporte.',
    pl: 'Aby uzyskać więcej informacji na temat tego, jak chronimy Twoje dane, skontaktuj się z naszym zespołem wsparcia.',
    ro: 'Pentru mai multe informații despre cum îți protejăm datele, te rugăm să contactezi echipa noastră de asistență.',
    sv: 'För mer information om hur vi skyddar dina uppgifter, vänligen kontakta vårt supportteam.',
  },
};
