export default {
  Welcome: {
    en: 'Welcome to {appName}! By using our platform, you agree to comply with the following terms and conditions. These terms are designed to protect your rights and privacy while using our services.',
    es: '¡Bienvenido a {appName}! Al usar nuestra plataforma, acepta cumplir con los siguientes términos y condiciones. Estos términos están diseñados para proteger sus derechos y privacidad mientras utiliza nuestros servicios.',
    nl: 'Welkom bij {appName}! Door gebruik te maken van ons platform gaat u akkoord met de volgende voorwaarden. Deze voorwaarden zijn ontworpen om uw rechten en privacy te beschermen tijdens het gebruik van onze diensten.',
    fr: 'Bienvenue sur {appName} ! En utilisant notre plateforme, vous acceptez de vous conformer aux termes et conditions suivants. Ces termes sont conçus pour protéger vos droits et votre vie privée lors de l\'utilisation de nos services.',
    de: 'Willkommen bei {appName}! Durch die Nutzung unserer Plattform stimmen Sie den folgenden Bedingungen zu. Diese Bedingungen sollen Ihre Rechte und Ihre Privatsphäre bei der Nutzung unserer Dienste schützen.',
    it: 'Benvenuto su {appName}! Utilizzando la nostra piattaforma, accetti di rispettare i seguenti termini e condizioni. Questi termini sono progettati per proteggere i tuoi diritti e la tua privacy durante l\'utilizzo dei nostri servizi.',
    ru: 'Добро пожаловать на {appName}! Используя нашу платформу, вы соглашаетесь соблюдать следующие условия. Эти условия направлены на защиту ваших прав и конфиденциальности при использовании наших услуг.',
    pt: 'Bem-vindo ao {appName}! Ao usar a nossa plataforma, você concorda em cumprir os seguintes termos e condições. Estes termos são projetados para proteger seus direitos e privacidade ao usar nossos serviços.',
    pl: 'Witamy na {appName}! Korzystając z naszej platformy, zgadzasz się przestrzegać poniższych warunków. Te warunki są zaprojektowane, aby chronić Twoje prawa i prywatność podczas korzystania z naszych usług.',
    ro: 'Bine ai venit la {appName}! Prin utilizarea platformei noastre, ești de acord să respecți următorii termeni și condiții. Acești termeni sunt concepuți pentru a proteja drepturile și confidențialitatea ta în timp ce utilizezi serviciile noastre.',
    sv: 'Välkommen till {appName}! Genom att använda vår plattform samtycker du till att följa följande villkor. Dessa villkor är utformade för att skydda dina rättigheter och din integritet när du använder våra tjänster.',
  },
  UserResponsibilities: {
    en: '1. User Responsibilities',
    es: '1. Responsabilidades del Usuario',
    nl: '1. Verantwoordelijkheden van de gebruiker',
    fr: '1. Responsabilités de l\'utilisateur',
    de: '1. Benutzerpflichten',
    it: '1. Responsabilità dell\'utente',
    ru: '1. Ответственности пользователя',
    pt: '1. Responsabilidades do usuário',
    pl: '1. Odpowiedzialność użytkownika',
    ro: '1. Responsabilitățile utilizatorului',
    sv: '1. Användarens ansvar',
  },
  UserResponsibilitiesDetails: {
    en: 'As a user of {appName}, you agree to use the platform responsibly, especially when creating or taking mock exams. Any content that violates our guidelines, including but not limited to inappropriate or illegal content, is strictly prohibited.',
    es: 'Como usuario de {appName}, acepta usar la plataforma de manera responsable, especialmente al crear o tomar exámenes simulados. Cualquier contenido que viole nuestras directrices, incluidos, entre otros, contenido inapropiado o ilegal, está estrictamente prohibido.',
    nl: 'Als gebruiker van {appName} stemt u ermee in om het platform op een verantwoorde manier te gebruiken, vooral bij het maken of afnemen van proefexamens. Alle inhoud die onze richtlijnen schendt, inclusief maar niet beperkt tot ongepast of illegaal materiaal, is ten strengste verboden.',
    fr: 'En tant qu\'utilisateur de {appName}, vous acceptez d\'utiliser la plateforme de manière responsable, notamment lors de la création ou de la passation d\'examens simulés. Tout contenu qui enfreint nos directives, y compris, mais sans s\'y limiter, les contenus inappropriés ou illégaux, est strictement interdit.',
    de: 'Als Benutzer von {appName} verpflichten Sie sich, die Plattform verantwortungsbewusst zu nutzen, insbesondere bei der Erstellung oder Teilnahme an simulierten Prüfungen. Jegliche Inhalte, die gegen unsere Richtlinien verstoßen, einschließlich, aber nicht beschränkt auf unangemessene oder illegale Inhalte, sind strengstens verboten.',
    it: 'In qualità di utente di {appName}, accetti di utilizzare la piattaforma in modo responsabile, soprattutto quando crei o sostieni esami simulati. Qualsiasi contenuto che violi le nostre linee guida, inclusi, a titolo esemplificativo ma non esaustivo, contenuti inappropriati o illegali, è severamente vietato.',
    ru: 'Как пользователь {appName}, вы обязуетесь использовать платформу ответственно, особенно при создании или прохождении пробных экзаменов. Любой контент, нарушающий наши правила, включая, но не ограничиваясь, неприемлемым или незаконным содержанием, строго запрещен.',
    pt: 'Como usuário do {appName}, você concorda em usar a plataforma de maneira responsável, especialmente ao criar ou realizar exames simulados. Qualquer conteúdo que viole nossas diretrizes, incluindo, entre outros, conteúdo inadequado ou ilegal, é estritamente proibido.',
    pl: 'Jako użytkownik {appName}, zobowiązujesz się do odpowiedzialnego korzystania z platformy, szczególnie podczas tworzenia lub rozwiązywania egzaminów próbnych. Wszelkie treści naruszające nasze wytyczne, w tym między innymi nieodpowiednie lub nielegalne treści, są surowo zabronione.',
    ro: 'Ca utilizator al {appName}, ești de acord să folosești platforma în mod responsabil, mai ales atunci când creezi sau participi la examene simulate. Orice conținut care încalcă liniile noastre directoare, inclusiv, dar fără a se limita la conținuturi inadecvate sau ilegale, este strict interzis.',
    sv: 'Som användare av {appName} samtycker du till att använda plattformen ansvarsfullt, särskilt när du skapar eller genomför prov. Innehåll som bryter mot våra riktlinjer, inklusive men inte begränsat till olämpligt eller olagligt innehåll, är strängt förbjudet.',
  },
  DataPrivacy: {
    en: '2. Data Privacy',
    es: '2. Privacidad de Datos',
    nl: '2. Gegevensbescherming',
    fr: '2. Confidentialité des données',
    de: '2. Datenschutz',
    it: '2. Privacy dei Dati',
    ru: '2. Конфиденциальность данных',
    pt: '2. Privacidade de Dados',
    pl: '2. Prywatność danych',
    ro: '2. Confidențialitatea datelor',
    sv: '2. Dataskydd',
  },
  DataPrivacyDetails: {
    en: 'We comply with the GDPR and take your privacy seriously. Your data will only be used for the purpose of providing the platform\'s services and will not be shared with third parties without your consent, except when required by law.',
    es: 'Cumplimos con el RGPD y nos tomamos en serio su privacidad. Sus datos solo se utilizarán para proporcionar los servicios de la plataforma y no se compartirán con terceros sin su consentimiento, excepto cuando lo exija la ley.',
    nl: 'Wij voldoen aan de AVG en nemen uw privacy serieus. Uw gegevens worden alleen gebruikt voor het leveren van de diensten van het platform en zullen niet worden gedeeld met derden zonder uw toestemming, behalve wanneer dit wettelijk vereist is.',
    fr: 'Nous respectons le RGPD et prenons votre vie privée au sérieux. Vos données ne seront utilisées que pour fournir les services de la plateforme et ne seront pas partagées avec des tiers sans votre consentement, sauf si la loi l\'exige.',
    de: 'Wir halten uns an die DSGVO und nehmen Ihre Privatsphäre ernst. Ihre Daten werden nur zum Zweck der Bereitstellung der Plattformdienste verwendet und nicht ohne Ihre Zustimmung an Dritte weitergegeben, es sei denn, dies ist gesetzlich vorgeschrieben.',
    it: 'Rispettiamo il GDPR e prendiamo sul serio la tua privacy. I tuoi dati verranno utilizzati solo per fornire i servizi della piattaforma e non saranno condivisi con terze parti senza il tuo consenso, salvo laddove richiesto dalla legge.',
    ru: 'Мы соблюдаем требования GDPR и серьезно относимся к вашей конфиденциальности. Ваши данные будут использоваться только для предоставления услуг платформы и не будут переданы третьим лицам без вашего согласия, за исключением случаев, предусмотренных законом.',
    pt: 'Cumprimos o RGPD e levamos a sua privacidade a sério. Os seus dados serão usados ​​apenas para fornecer os serviços da plataforma e não serão compartilhados com terceiros sem o seu consentimento, exceto quando exigido por lei.',
    pl: 'Zgodnie z RODO poważnie podchodzimy do Twojej prywatności. Twoje dane będą wykorzystywane wyłącznie w celu świadczenia usług platformy i nie będą udostępniane osobom trzecim bez Twojej zgody, chyba że jest to wymagane przez prawo.',
    ro: 'Respectăm GDPR și luăm în serios confidențialitatea ta. Datele tale vor fi utilizate doar pentru a oferi serviciile platformei și nu vor fi partajate cu terți fără consimțământul tău, cu excepția cazurilor prevăzute de lege.',
    sv: 'Vi följer GDPR och tar din integritet på allvar. Dina uppgifter kommer endast att användas för att tillhandahålla plattformens tjänster och kommer inte att delas med tredje part utan ditt samtycke, förutom när det krävs enligt lag.',
  },
  IntellectualProperty: {
    en: '3. Intellectual Property',
    es: '3. Propiedad Intelectual',
    nl: '3. Intellectueel eigendom',
    fr: '3. Propriété intellectuelle',
    de: '3. Geistiges Eigentum',
    it: '3. Proprietà intellettuale',
    ru: '3. Интеллектуальная собственность',
    pt: '3. Propriedade intelectual',
    pl: '3. Własność intelektualna',
    ro: '3. Proprietatea intelectuală',
    sv: '3. Immateriell egendom',
  },
  IntellectualPropertyDetails: {
    en: 'The content you create, including questions and study materials, remains your intellectual property. However, by using the platform, you grant us a license to use, modify, and distribute the content within the platform.',
    es: 'El contenido que crea, incluidas las preguntas y los materiales de estudio, sigue siendo de su propiedad intelectual. Sin embargo, al usar la plataforma, nos otorga una licencia para usar, modificar y distribuir el contenido dentro de la plataforma.',
    nl: 'De inhoud die u maakt, inclusief vragen en studiemateriaal, blijft uw intellectuele eigendom. Door het platform te gebruiken, verleent u ons echter een licentie om de inhoud binnen het platform te gebruiken, te wijzigen en te distribueren.',
    fr: 'Le contenu que vous créez, y compris les questions et les documents d\'étude, reste votre propriété intellectuelle. Cependant, en utilisant la plateforme, vous nous accordez une licence pour utiliser, modifier et distribuer le contenu au sein de la plateforme.',
    de: 'Die Inhalte, die Sie erstellen, einschließlich Fragen und Lernmaterialien, bleiben Ihr geistiges Eigentum. Durch die Nutzung der Plattform gewähren Sie uns jedoch eine Lizenz, die Inhalte innerhalb der Plattform zu nutzen, zu ändern und zu verbreiten.',
    it: 'Il contenuto che crei, comprese le domande e i materiali di studio, rimane tua proprietà intellettuale. Tuttavia, utilizzando la piattaforma, ci concedi una licenza per utilizzare, modificare e distribuire il contenuto all\'interno della piattaforma.',
    ru: 'Контент, который вы создаете, включая вопросы и учебные материалы, остается вашей интеллектуальной собственностью. Однако, используя платформу, вы предоставляете нам лицензию на использование, изменение и распространение этого контента в рамках платформы.',
    pt: 'O conteúdo que você cria, incluindo perguntas e materiais de estudo, permanece sua propriedade intelectual. No entanto, ao usar a plataforma, você nos concede uma licença para usar, modificar e distribuir o conteúdo dentro da plataforma.',
    pl: 'Treści, które tworzysz, w tym pytania i materiały do ​​nauki, pozostają Twoją własnością intelektualną. Jednakże, korzystając z platformy, udzielasz nam licencji na korzystanie, modyfikowanie i rozpowszechnianie treści w ramach platformy.',
    ro: 'Conținutul pe care îl creezi, inclusiv întrebările și materialele de studiu, rămâne proprietatea ta intelectuală. Totuși, folosind platforma, ne acorzi o licență pentru a utiliza, modifica și distribui conținutul în cadrul platformei.',
    sv: 'Innehållet du skapar, inklusive frågor och studiematerial, förblir din immateriella egendom. Genom att använda plattformen ger du oss dock en licens att använda, modifiera och distribuera innehållet inom plattformen.',
  },
  LimitationOfLiability: {
    en: '4. Limitation of Liability',
    es: '4. Limitación de Responsabilidad',
    nl: '4. Aansprakelijkheidsbeperking',
    fr: '4. Limitation de responsabilité',
    de: '4. Haftungsbeschränkung',
    it: '4. Limitazione di responsabilità',
    ru: '4. Ограничение ответственности',
    pt: '4. Limitação de Responsabilidade',
    pl: '4. Ograniczenie odpowiedzialności',
    ro: '4. Limitarea răspunderii',
    sv: '4. Ansvarsbegränsning',
  },
  LimitationOfLiabilityDetails: {
    en: '{appName} is not responsible for any damages or losses arising from the use of the platform. We do our best to provide reliable services but do not guarantee uninterrupted access or data accuracy.',
    es: '{appName} no es responsable de ningún daño o pérdida que surja del uso de la plataforma. Hacemos todo lo posible para ofrecer servicios confiables, pero no garantizamos el acceso ininterrumpido ni la precisión de los datos.',
    nl: '{appName} is niet verantwoordelijk voor enige schade of verliezen die voortvloeien uit het gebruik van het platform. We doen ons best om betrouwbare diensten te leveren, maar garanderen geen ononderbroken toegang of nauwkeurigheid van gegevens.',
    fr: '{appName} n\'est pas responsable des dommages ou pertes résultant de l\'utilisation de la plateforme. Nous faisons de notre mieux pour fournir des services fiables, mais nous ne garantissons pas un accès ininterrompu ou l\'exactitude des données.',
    de: '{appName} haftet nicht für Schäden oder Verluste, die sich aus der Nutzung der Plattform ergeben. Wir bemühen uns, zuverlässige Dienste bereitzustellen, garantieren jedoch keinen ununterbrochenen Zugang oder die Genauigkeit der Daten.',
    it: '{appName} non è responsabile per eventuali danni o perdite derivanti dall\'uso della piattaforma. Facciamo del nostro meglio per fornire servizi affidabili, ma non garantiamo un accesso ininterrotto o l\'accuratezza dei dati.',
    ru: '{appName} не несет ответственности за какие-либо убытки или ущерб, возникшие в результате использования платформы. Мы делаем все возможное, чтобы предоставлять надежные услуги, но не гарантируем непрерывный доступ или точность данных.',
    pt: '{appName} não se responsabiliza por quaisquer danos ou perdas decorrentes do uso da plataforma. Fazemos o possível para fornecer serviços confiáveis, mas não garantimos acesso ininterrupto ou precisão de dados.',
    pl: '{appName} nie ponosi odpowiedzialności za jakiekolwiek szkody lub straty wynikające z korzystania z platformy. Dokładamy wszelkich starań, aby zapewnić niezawodne usługi, ale nie gwarantujemy nieprzerwanego dostępu ani dokładności danych.',
    ro: '{appName} nu este responsabil pentru daunele sau pierderile care decurg din utilizarea platformei. Facem tot posibilul pentru a oferi servicii de încredere, dar nu garantăm accesul neîntrerupt sau acuratețea datelor.',
    sv: '{appName} ansvarar inte för eventuella skador eller förluster som uppstår vid användning av plattformen. Vi gör vårt bästa för att tillhandahålla tillförlitliga tjänster men garanterar inte oavbruten åtkomst eller dataexakthet.',
  },
  Acknowledge: {
    en: 'By continuing to use the platform, you acknowledge that you have read and agree to these terms.',
    es: 'Al continuar usando la plataforma, usted reconoce que ha leído y acepta estos términos.',
    nl: 'Door de platform te blijven gebruiken, erkent u dat u deze voorwaarden hebt gelezen en ermee akkoord gaat.',
    fr: 'En continuant à utiliser la plateforme, vous reconnaissez avoir lu et accepté ces termes.',
    de: 'Durch die fortgesetzte Nutzung der Plattform erkennen Sie an, dass Sie diese Bedingungen gelesen haben und ihnen zustimmen.',
    it: 'Continuando a utilizzare la piattaforma, riconosci di aver letto e accettato questi termini.',
    ru: 'Продолжая пользоваться платформой, вы подтверждаете, что прочитали и согласны с этими условиями.',
    pt: 'Ao continuar a usar a plataforma, você reconhece que leu e concorda com estes termos.',
    pl: 'Kontynuując korzystanie z platformy, potwierdzasz, że zapoznałeś się i zgadzasz się z tymi warunkami.',
    ro: 'Continuând să folosești platforma, recunoști că ai citit și ești de acord cu acești termeni.',
    sv: 'Genom att fortsätta använda plattformen bekräftar du att du har läst och godkänner dessa villkor.',
  },
};
